# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BayStateAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('deposit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CommonWealthAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NULL', max_length=50)),
                ('auction_date', models.CharField(default='NULL', max_length=20)),
                ('auction_time', models.CharField(default='NULL', max_length=20)),
                ('address', models.TextField()),
                ('country', models.CharField(default='NULL', max_length=20)),
                ('deposit', models.CharField(default='NULL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='NULL', max_length=50)),
                ('text', models.TextField(default='Null')),
            ],
        ),
        migrations.CreateModel(
            name='HarkinRealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('zipcode', models.IntegerField()),
                ('deposit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LandMarkAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_date', models.CharField(max_length=20)),
                ('time', models.CharField(default='NULL', max_length=10)),
                ('status', models.CharField(default='NULL', max_length=50)),
                ('address', models.TextField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='PatriotAuctioneer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('terms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('zipcode', models.IntegerField()),
                ('terms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SullivanAuctioneers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('terms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TacheAuctionAndSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('deposit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TownAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('deposit', models.CharField(max_length=10)),
            ],
        ),
    ]
