# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_auto_20171005_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonwealthauction',
            name='auction_date',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='commonwealthauction',
            name='auction_time',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='commonwealthauction',
            name='country',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='commonwealthauction',
            name='deposit',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='commonwealthauction',
            name='status',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
