# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0006_auto_20171007_1832'),
    ]

    operations = [
    ]
