# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0009_auto_20171028_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='baystateauction',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonwealthauction',
            name='city',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='commonwealthauction',
            name='state',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='landmarkauction',
            name='deposit',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='landmarkauction',
            name='city',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='landmarkauction',
            name='state',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='landmarkauction',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
