# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0011_commonwealthauction_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesco',
            old_name='title',
            new_name='status',
        ),
    ]
