# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0012_auto_20171029_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesco',
            old_name='status',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='commonwealthauction',
            name='city',
        ),
    
        migrations.AlterField(
            model_name='commonwealthauction',
            name='zipcode',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='harkinrealestate',
            name='zipcode',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='pesco',
            name='zipcode',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='tacheauctionandsales',
            name='zipcode',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='townauction',
            name='zipcode',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
