# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0014_auto_20171106_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baystateauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 4, 46, 113410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='harkinrealestate',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 4, 46, 114863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='landmarkauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 4, 46, 110872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patriotauctioneer',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 4, 46, 118687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pesco',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 4, 46, 115564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sullivanauctioneers',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 4, 46, 118029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tacheauctionandsales',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 4, 46, 117258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='townauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 4, 46, 116475, tzinfo=utc)),
        ),
    ]
