# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0016_auto_20171106_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baystateauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 27, 457620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='harkinrealestate',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 27, 459475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='landmarkauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 27, 453760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patriotauctioneer',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 27, 466407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pesco',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 27, 460393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sullivanauctioneers',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 27, 465331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tacheauctionandsales',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 27, 463916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='townauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 27, 462021, tzinfo=utc)),
        ),
    ]
