# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0017_auto_20171106_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baystateauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 36, 629483, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='harkinrealestate',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 36, 631984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='landmarkauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 36, 625551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patriotauctioneer',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 36, 638187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pesco',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 36, 633170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sullivanauctioneers',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 36, 637234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tacheauctionandsales',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 36, 635943, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='townauction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 20, 48, 36, 634658, tzinfo=utc)),
        ),
    ]
