# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0018_auto_20171106_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baystateauction',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
        migrations.AlterField(
            model_name='commonwealthauction',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
        migrations.AlterField(
            model_name='harkinrealestate',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
        migrations.AlterField(
            model_name='landmarkauction',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
        migrations.AlterField(
            model_name='patriotauctioneer',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
        migrations.AlterField(
            model_name='pesco',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
        migrations.AlterField(
            model_name='sullivanauctioneers',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
        migrations.AlterField(
            model_name='tacheauctionandsales',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
        migrations.AlterField(
            model_name='townauction',
            name='date',
            field=models.DateField(default=datetime.date(2017, 11, 7)),
        ),
    ]
